# .github/workflows/keep-alive.yml
name: Keep My App Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          curl -I https://real-estate-leads.onrender.com/ || true
